name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - actions
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build: # make sure build/ci work properly
  
    runs-on: macOS-latest
    timeout-minutes: 30
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
